#
language: python

env:
  global:
    - NO_NET=1

git:
  depth: 10

branches:
  only:
    - master

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      services:
        - xvfb
      # before_script: # configure a headless display to test plot generation
      #   - "export DISPLAY=:99.0"
      #   - "sh -e /etc/init.d/xvfb start"
      #   - sleep 3 # give xvfb some time to start

# Install dependencies
install:
  - pip install -r requirements.travis.txt
  - pip install -e .
  - pip install --upgrade pip
  - pip install codecov
  - pip install pytest-cov
  - pip install codacy-coverage

# command to run tests
script:
  - py.test ./tests --cov=waterbalans --cov-report=xml
after_success:
   - python-codacy-coverage -r coverage.xml
