#
language: python

env:
  global:
    - NO_NET=1

git:
    depth: 1000

matrix:
  include:
      - python: 3.7
        dist: xenial
        sudo: true
        # services:
        #   - xvfb
        # before_script:
        #   - sleep 3 # give xvfb some time to start

# Install dependencies
install:
    - pip install -r requirements.travis.txt
    - pip install -e .
    - pip install --upgrade pip
    - pip install codecov
    - pip install pytest-cov

# command to run tests
script:
   - py.test ./tests --cov=waterbalans --cov-report=xml

after_success:
   - codecov